### ISSUE TITLE
e-Commerce Plugin 

### ISSUE THREAD

**Issue by stevebrainng** [juzaweb/cms#190]
First before anything I must confess that this is a Brilliant piece of a project and I highly commend you for your Work. Replicating wordpress is one big work anyone can commit to. I hope more people see the Light here.

Woocommerce Like **eCommerce** Platform with Payment Interface which other plugin can utilize.

I am also curious about how I can use this Cms and a Saas Application. 
[
  Multi User based Sub-domains & Domain,
  Multi-User permission e.g: **Admin** has -->**Content Creators** has-> customers, authors.
  Content Creators are able to create thier own content.
  Content Creators have to subscribe to Subscription Package to be able to add, edit.
]

I will make contributions as time goes on Thanks.

**Comment by juzaweb** [comment]
Hi @stevebrainng 
Thanks for your contributions. We are also developing e-Commerce Plugin for this cms, you can see it at https://github.com/juzaweb/ecommerce. However, it is not completed yet. If you want you can contribute to this plugin. It doesn't matter if a plugin is different from another vendor, contributions from the community are always welcome.
You can use this cms for anything, it is open source, but please don't delete, rebrand in your cms (based GNU General Public License v2.0).
