### ISSUE TITLE
Edit page does not show current content

### ISSUE THREAD

**Issue by kobato-chan1912** [juzaweb/cms#208]
Edit page of the latest version doesn't show current content. The title and description input is null. 
Can you check this?

**Comment by juzaweb** [comment]
I fixed in version 3.2.2, thanks for report

**Comment by kobato-chan1912** [comment]
Hello, I have just found new error: The chart post view in dashboard doesn't update. 
I have checked the post_views table and got the views in each posts, but the chart post in dashboard doesn't update the views.

**Comment by kobato-chan1912** [comment]
Bonus: The top views table in dashboard got the same error.

**Comment by juzaweb** [comment]
The chart post view/top views table in dashboard doesn't update in real time. It is updated once every hour

**Comment by kobato-chan1912** [comment]
Okay. I got it.
Thanks for helping me. 
Love this project ❤
