### ISSUE TITLE
Custom SEO

### ISSUE THREAD

**Issue by anielka41** [juzaweb/cms#218]
Hi,
let me set up a few themes with missing features.

The basics of SEO settings are missing:
1. Cannonical link
2. nofollow/follow & noindex/index

**Comment by juzaweb** [comment]
Yes, I'm very happy about that.
Please let me know in advance your ideas and how to implement them?

**Comment by anielka41** [comment]
All options are in the picture here: https://ahrefs.com/blog/wp-content/uploads/2019/12/canonical-yoast.png
I am not a programmer, I am an SEO specialist.

**Comment by anielka41** [comment]
[Social previews](https://yoast.com/features/content-previews/social-previews/)

**Comment by juzaweb** [comment]
We will refer to them in the future, thanks for your suggestions
