### ISSUE TITLE
Bug - admin prefix

### ISSUE THREAD

**Issue by anielka41** [juzaweb/cms#220]
Hi,
change prefix:
'admin_prefix' => env('ADMIN_PREFIX', 'admin-cp'),

routing doesn't work in many places. Everything works fine with 'admin-cp'

**Comment by juzaweb** [comment]
Thanks for your report, we will check it.

**Comment by anielka41** [comment]
Ok. Check the admin bar on the front. Check the translation plugin. And other paths.

**Comment by juzaweb** [comment]
Fixed in version v3.2.5
