### ISSUE TITLE
Update - not working

### ISSUE THREAD

**Issue by anielka41** [juzaweb/cms#225]
Hi,
I made the update in the administration panel.

"You are using Juzaweb CMS Version: v3.2.3
View CMS [change logs here](https://github.com/juzaweb/juzacms/releases)
Version 3.2.4 ready to update."

The page has not updated and is constantly being updated without upgrading the version.

Additionally. I remove notifications here: /admin-cp/notification
The notifications in the upper right corner do not disappear. (next to the user's avatar)

**Comment by juzaweb** [comment]
I don't understand your update problem, please explain more about it.

**Comment by anielka41** [comment]
1. Click update.
2. The update progress continues.
3. The update ends.
4. The CMS version does not change.
I can repeat this process over and over again.

**Comment by juzaweb** [comment]
I'm sorry, it was our mistake. I think your version has been updated. Version in CMS is wrong

**Comment by anielka41** [comment]
ok
