### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by mesiarm** [juzaweb/cms#233]
I ´ve made list of feature requests when compared to Wordpress (with some plugins):

Posts, Pages Translation (like WPML)
Custom Fields in Posts, Pages, settings page (LIKE ACF)
Ability to switch backend language
handle custom ajax - custom api routes like wp-ajax in theme
page, post revisions
form creator (like Contact Form 7) with recaptcha and mailchimp support
cache
monitor 404

**Comment by juzaweb** [comment]
Thanks for your suggestions, we will consider including them in the future
