### ISSUE TITLE
filesystem driver must have an adapter implemented

### ISSUE THREAD

**Issue by delgerdev** [juzaweb/cms#245]
when uploading a image in text editor occurs "filesystem driver must have an adapter implemented" message in red color.

**Comment by juzaweb** [comment]
did you edit the filemanager disk config?

**Comment by delgerdev** [comment]
No, I chose juzacms 1.2.5 because my development environment's php version is 7.4. Should I install the laravel-filemanager package?. where is the config filemanager disk config file? I haven't edited any configuration files.

**Comment by delgerdev** [comment]
> did you edit the filemanager disk config?

No, I chose juzacms 1.2.5 because my development environment's php version is 7.4. Should I install the laravel-filemanager package?. where is the config filemanager disk config file? I haven't edited any configuration files.

**Comment by juzaweb** [comment]
wow, you're using a pretty old version for me
you don't have to install laravel-filemanager package, please double check some things
- Your folder `storage` permissions
- Publich your config file `php artisan vendor:publish --tag=juzaweb_config` and check filemanager disk config
- Make sure config `filesystems.php` has disk `local`
