### ISSUE TITLE
[Multisite] Routes admin-cp/network does not work

### ISSUE THREAD

**Issue by ghost** [juzaweb/cms#293]
Hello!

I am trying to install the network module in JuzaCMS. I could manually import both migration files and have created the tables, namely network_sites,network_databases and network_domain_mappings. 

In the config.network.php, I have by derfault JW_ALLOW_MULTISITE', false.

The moment I set JW_ALLOW_MULTISITE', true, it throws 404. This means obviously routes are not there.

Is this area available to work with?

**Comment by juzaweb** [comment]
- You need to configure 2 variables below to make sure the network works. Let's check it again
```
JW_ALLOW_MULTISITE=true
JW_NETWORK_ROOT_DOMAIN=yourdomain.com
```
- Try running command
`php artisan optimize:clear`

**Comment by DeRaja** [comment]
Hello!
Thanks for your answer and taking time.

I have done all that basic things before posting this message. I was able to generate DB tables and seed them. But they all got created in the same database. Sorry about this that I forgot to mention.

Further, the network route does not work and throws 404 error on front- and backend.

**Comment by juzaweb** [comment]
What version are you using?
Routers are defined in:
[modules/Network/Providers/NetworkServiceProvider.php](https://github.com/juzaweb/juzacms/blob/develop/modules/Network/Providers/RouteServiceProvider.php#L21)
and Provider registed in
[modules/CMS/Providers/CmsServiceProvider.php](https://github.com/juzaweb/juzacms/blob/develop/modules/CMS/Providers/CmsServiceProvider.php#L368)
Check them out and make sure they're in the right place.
Take a picture of your error and send it to me, if possible!

**Comment by juzaweb** [comment]
Run command `php artisan juzacms:clear-cache` and try again.
This happens when you use a cache driver other than the default.

**Comment by DeRaja** [comment]
Hello!

Thanks. Cache is not an issue here. I have manually removed all the files generated under storage manually, to force generate them.

Under the route /admin-cp, the third link seen in the demo of "Network" and that dropdown does not get listed there. The drop down is missing. 

If I manually type the route /admin-cp/network/sites, I get 404. This is the problem.

Can you please suggest how I can have the route /admin-cp/network/sites to work?

**Comment by juzaweb** [comment]
What version are you using?
Have you published the cms config yet?

**Comment by DeRaja** [comment]
Hello!
Thanks.
I have installed everything for the first time in the last three days. 
This is Laravel 9.45 framework.
It would be really the best if you can give a step by step instruction on getting the Network working.
It really does not help others, who are interested to use your marvellous work, if you ask things that are fragments of your assumptions. I know that you are trying to be very helpful. But it appears that there must be one tiny step that I have not done.

Is there anywhere a step-by-step guide on how to get your project working?

You have put 100s of hours in coding and creating this marvellous piece of work. Please invest one hour to write on how to make this work as a step-by-step guide. This one hour will make use of your work very effective and inspire starters like me to use it.

**Comment by DeRaja** [comment]
Hello!
I believe that you may be trying to make things work on localhost. 
But I am doing with real subdomains online.

The Network link I mentioned does not appear on the master domain. But I could manually generate migrations on artisan. These database tables gets created only in the same database of network_sites because there is no information on connection to a subdomain_site2.

So this whole area seems to be missing something in my case. But you cannot see this, if you are on localhost.

The first important thing is to be able to get the Network route working so that I can configure the site and database information in the database.

**Comment by DeRaja** [comment]
Hello!

> Have you published the cms config yet?

If you want to know, then following files are in the directory:
/CMS/config/juzaweb.php
/CMS/config/network.php

It has:
return [
    'enable' => env('JW_ALLOW_MULTISITE', true),
    'domain' => env('JW_NETWORK_ROOT_DOMAIN')
];

as well as:
     */
    'admin_prefix' => env('ADMIN_PREFIX', 'admin-cp'),

Can it be that I need to add something in this file manually to get the routes of network working?

**Comment by ghost** [comment]
Hello!

I found the problem.  During the DB Migrations, there were severe crashes because of primary keys. Currently, the migration files are not compatible with MariaDB (I have not tested on mysql). So I needed to add primary keys. Here, tables got generated but there were defects in the columns, etc. Not worth describing here where and how that happened.

But after creating multiple times, things have started working. I can now see the Network menu in admin-cp after activating multisite in env file, as suggested JW_NETWORK_ROOT_DOMAIN = yourdomain.com.

This project is really one of the best ever I have seen on laravel plattform and will close this one, as I was able to solve it.

I have opened a new issue here:

[MariaDB] Migrations not compatible with MariaDB #296
