### ISSUE TITLE
[CMS] Seperate Pages and Posts

### ISSUE THREAD

**Issue by ghost** [juzaweb/cms#294]
Hello!

I configured pages and posts. But I see they are saved in the same table by a difference in parameter "types".

This will case lots of troubles because both cannot be customized. They both have different tables and the data should be saved in their respective tables. Only then we can make specific customization of them individually accordance to our needs, which may differ netween pages and posts.

**Comment by juzaweb** [comment]
Hello!
The database of this project is inspired by Wordpress database design. 
You can see more:
https://codex.wordpress.org/Database_Description

You can create custom columns in the post_metas table!

**Comment by ghost** [comment]
Hi!
Thanks for your answer. Sorry, I was not clear in my post above.

By default, there are two seperate tables created by migrations, tableprefix_pages and tableprefix_posts. 

But all the content I have created, gets into one table tableprefix_posts only. During creation, I had chosen the type of that content as page. So, it has saved the type in the type column in this table instead of saving that content in the table of tableprefix_pages.

I expected following should happen after creating content:

content--->page--->tableprefix_page
content--->post--->tableprefix_posts

There is a table tableprefix_page. It has columns regarding templates. I had expected everything to be saved in this table. 

However, upon choosing the template, everything got saved in the column json_metas in the table tableprefix_posts.

As a result, the table tableprefix_page IS EMPTY!

Hence, I posted this as a request that bot these tables, after having been created, should be used instead of mixing it in the same table and having an extra data in json_metas for pages.
