### ISSUE TITLE
[MariaDB] Migrations not compatible with MariaDB

### ISSUE THREAD

**Issue by ghost** [juzaweb/cms#296]
Hello!

During migrations, I was forced to make changes in the primary keys of multiple php files in version 1.0.5, 2.0 and 3.0 because I am using MariaDB. For example:

In the file 2021_03_10_031508_create_term_taxonomies_table.php I had to add $table->bigIncrements('tid'); 

One possibility is to provide one SQL file for MariaDB while keeping current migrations files the same. Then, one can manually import it. Or modify migrations such that it works for both databases.

**Comment by juzaweb** [comment]
Why do you have to change the primary key? I don't understand what your problem is?
