### ISSUE TITLE
[MultisiteDB] Creation of the database in network_databases of a new site from admin panel

### ISSUE THREAD

**Issue by ghost** [juzaweb/cms#297]
Hello!

I have a fully functioning demo working on my server. I am able to create a new subdomain.com as site 1. For this, the Module is creating tables prefix_site1_*_* in the same database. I have tried to create it via artisan and the result was the same.

There is no possibility to enter through web interface the database connections. How can I achieve seperation of databases? 

If not and I have 20 subdomains, then it will create too many tables in one single database.

**Comment by juzaweb** [comment]
Yes! It will create a separate database for each of your subsites. If you have any suggestions for improvement? leave it here
