### ISSUE TITLE
[Translation] Save translated data in final jw_translations from language_lines and ability to delete languages

### ISSUE THREAD

**Issue by ghost** [juzaweb/cms#298]
Hello!

I have imported translations on artisan. Now there are 5100 records in the jw_translations table.

There are multiple languages in this table, 8x. I only need two or three. I can keep it but it would be better to have a possibility to delete it.

I started translating after adding a new language. But this got saved in a new table language_lines and I cannot access it directly or easily. It is saved in json format in the column. I would like an easy access directly in columns, just like it is in jw_translations, after translation.

In the table language_lines, if this should be used finally, a column locale_code is missing.

Is it possible to enter the translated values in the jw_translations such that it has the language code as a varient, like de, hi, or any other language?

**Comment by juzaweb** [comment]
Hello!
jw_translations is an automatic translation intermediate table for developers, this table will be exported as php and json files for themes and plugins. If you edit the version in the CMS, it will be applied immediately to your website and stored in the language_lines table. language_lines table is designed to make your site run faster with custom translations so there is no locale code on each line.
