### ISSUE TITLE
juzawebCMS v3.4 has an XSS vulnerability in the comment section.

### ISSUE THREAD

**Issue by W01fh4cker** [juzaweb/cms#355]
1. log in as user `aaa@aaa` and post a comment `<script>alert(1)</script>`.  
![image](https://github.com/juzaweb/cms/assets/101872898/7f30ef36-9838-4ba9-8b79-12ed039bc74c)

2. Log in to the admin backend to trigger a stored XSS vulnerability.  
![image](https://github.com/juzaweb/cms/assets/101872898/d473fd47-0a6e-447a-bf44-56c5c9217098)

**Comment by juzaweb** [comment]
Hello
It seems like it doesn't come from the comment but from your post title. We will fix them as soon as possible.
Thanks for report.
