### ISSUE TITLE
get_post_resources(): Argument #1 ($resource) must be of type string

### ISSUE THREAD

**Issue by freddiehdxd** [juzaweb/cms#358]
when l add a movie and try to access the movie l get this error 
get_post_resources(): Argument #1 ($resource) must be of type string, array given, called in /www/wwwroot/domain.com/storage/framework/views/twig/a5/a5ab391fe69d8d895c4ff42259467eca.php on line 68

**Comment by juzaweb** [comment]
Can you tell me the cms version you are using?

**Comment by juzaweb** [comment]
I know the cause of your error, please open the file
`themes/mymo/views/template-parts/single-movie.twig`
find line
`{% set servers = get_post_resources(post, 'servers') %}`
replaced by
`{% set servers = get_post_resources('servers', {'post_id': post.id}) %}`
Or re-download the theme, thank you
