### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by umut77** [juzaweb/cms#83]
After runing composer install I am getting this

`> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Missing vendor files, try running "composer install" or use the Wizard installer.
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
umut@Umuts-MacBook-Pro laravel % php artisan mymo:install

Missing vendor files, try running "composer install" or use the Wizard installer.
`

**Comment by Harsh-123rgb** [comment]
Can you Please Give a Video tutorial or written tutorial for Installation of this script on cPanel

Because I'm getting the same error - 
Missing vendor files, try running "composer install" or use the Wizard installer.

Please Provide a Better Documentation for Cpanel Servers .

I really like this script and Wants to Install but I'm not able to do since 15 days I've tried Many times..

Please provide a Video tutorial or text docs for Cpanel Servers.

Thanks

**Comment by juzaweb** [comment]
Please run composer install to install vendors, This is a [laravel](https://laravel.com/) source code

**Comment by Harsh-123rgb** [comment]
Sir I've tried by running Composer but it didn't worked for me.

It would be grateful if you Explain exact list of commands here sir. Because php artisan mymo:install also doesn't work for me.

Thanks

**Comment by Harsh-123rgb** [comment]
Sir I've successfully installed it but sir I'm facing an error on live website [Website Url](www.fix.growthcruise.xyz) 

Please check and tell what is wrong with it

**Comment by Harsh-123rgb** [comment]
Sir I've installed cms but it is ver different from https://mymo.juzaweb.com/

I want this script please tell me from where i can get this??

**Comment by juzaweb** [comment]
> Sir I've installed cms but it is ver different from https://mymo.juzaweb.com/
> 
> I want this script please tell me from where i can get this??

Maybe you are wrong, this is cms for laravel, not movie script

**Comment by juzaweb** [comment]
You can buy it here https://www.codester.com/items/25039/mymo-tv-series-and-movie-portal-cms-unlimited

**Comment by Harsh-123rgb** [comment]
> You can buy it here https://www.codester.com/items/25039/mymo-tv-series-and-movie-portal-cms-unlimited

Is this Lifetime license for unlimited domain??? and Lifetime support & updates?
