### ISSUE TITLE
about mymocms

### ISSUE THREAD

**Issue by c0py7hat** [juzaweb/cms#87]
Can you share the source code of this website https://mymo.juzaweb.com/ ? The website program is great, I really want it.

**Comment by juzaweb** [comment]
You can download it https://juzaweb.com/download/

**Comment by Harsh-123rgb** [comment]
> You can download it https://juzaweb.com/download/

Yes I downloaded and installed all plugins but there are many issues with it login doesn't Work and 404 page is not similar to Codestor's MyMo CMS.


So Can you Please provide the Same MyMo CMS movie Script from Codestor.

I've also asked you in Facebook 
If you can't share here please send link in facebook

Please give it's Download links

**Comment by Harsh-123rgb** [comment]
> You can download it https://juzaweb.com/download/

 please reply above comments

**Comment by juzaweb** [comment]
You can install cms and 
Go to Admin -> Themes -> Add new
Search and add mymo theme active it

**Comment by Harsh-123rgb** [comment]
> You can install cms and Go to Admin -> Themes -> Add new Search and add mymo theme active it

Yes done, but Login and register doesn't works, and some times get error on filter and home page
